### ISSUE TITLE
data-drive-test example has wrong (swaped) title 

### ISSUE THREAD

**Issue by cadu-leite** [robotframework/HowToWriteGoodTestCases#6]
Topic link: https://github.com/robotframework/HowToWriteGoodTestCases/blob/master/HowToWriteGoodTestCases.rst#data-driven-tests

I believe the titles are inverted ... 
 "test Case" title should be  "Keywords" and "*vice-versa*"

```
*** Test Cases ***  # <-- ERROR ...  it should be "keywords"
    USERNAME             PASSWORD  
    Invalid Username      invalid              ${VALID PASSWORD}
...
```
e

```
*** Keywords ***  # <-- ERROR ...  it should be "Test Cases"
Login with invalid credentials should fail
    [Arguments]    ${username}    ${password}
    Input Username    ${username}
   ...
```

**Comment by Tattoo** [comment]
Thanks for contributing! However, the headings are correct in this order.
